project/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :sounds
      resources :posts
      resources :tracks

      root to: "sounds#index"
    end
  resources :posts
  devise_for :sounds

  resources :sounds, only: [:index, :show] do
      resources :tracks
  end

  authenticated :sound do
    root 'sounds#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'


end

project/app/models/sound.rb
class Sound < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :tracks

  has_attached_file :thumbnail, :styles => { :medium => "200x200#" }
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/
end

project/app/controllers/admin/sounds_controller.rb
module Admin
  class SoundsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Sound.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Sound.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

project/app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
	before_action :find_sound, only: [:show, :dashboard]
	before_action :find_track, only: [:show, :dashboard]

	def index
		@sounds = Sound.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
	end

	def show
	end

	def dashboard
	end

	private

	def find_track
		@tracks = Track.where(sound_id: @sound).order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
	end

	def find_sound
		if params[:id].nil?
			@sound = current_sound
		else
			@sound = Sound.find(params[:id])
		end
	end
end

project/app/helpers/sounds_helper.rb
module SoundsHelper
end

project/app/views/sounds/dashboard.html.erb
<header id="main_header" class="cf">
	<div class="wrapper_wide">
		<%= link_to "OpenSound", root_path, id: "logo" %>
		<nav>
			<ul>
	
				<% unless sound_signed_in? %>
					<li><%= link_to "Explore", sound_session_path %></li>
					<li><%= link_to "Sign In", new_sound_session_path %></li>
					<li><%= link_to "Share a Sound", new_sound_registration_path %></li>
				<% else %>
					
					<li><%= link_to "Upload New Track!", new_sound_track_path(@sound)  %></li>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "Explore",sounds_path %></li>
					<li><%= link_to "Sign Out", destroy_sound_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

   
  <div id="sound_show">
	<div id="show_banner">
	    <h1>User dashboard.</h1>
	

    </div>
  
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>

	<div id="page">
    <div class="wrapper_skinny">
      <ul>
			<h2> Personal Page. </h2>
        <li>User ID: <%= @sound.id %></li>
        <li>User e-mail: <%= @sound.email %></li>
        <li><%= link_to "Audio Upload", new_sound_track_path(@sound)  %></li>
        <li><%= link_to "Edit Registration", edit_sound_registration_path %></li>
			</ul>
		</div>
	</div>


	<div id="tracks">
    <div class="wrapper_skinny">
		<h4>Shared Audios</h4>
      <ul class="cf">
        <% @tracks.each do |track| %>
          <li class="cf">
            <div class="track_thumbnail">
              <a href="#">
                <%= image_tag track.track_thumbnail.url(:medium) %>
              </a>
            </div>
            <div class="track_overview">
              <h2><%= link_to track.title, sound_track_path(@sound, track) %></h2>
              <p class="description"><%= truncate(track.description, lenght: 160) %></p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_sound_track_path(@sound, track) %>
                <%= link_to "Delete", sound_track_path(@sound, track), method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>


<%= will_paginate @tracks, previous_label: "Previous", next_label: "Next" %>
</div>

project/app/views/sounds/index.html.erb
<div id="sound_show">
	<div id="show_banner">
	<h1>Find out your new fav sound.</h1>
	</div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
				<li><%= link_to "Account Settings", edit_sound_registration_path(current_sound) %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>
      </ul>
    </div>
  </div>


<div id="sounds" class="cf">
	<div class="wrapper">

			<h3> OpenSound </h3>

            <h4>Check Available Authenticated Versions:</h4>
            <ul>
			<li>Version 1.0.1</li>
            <% if current_sound %>
            <li>Version 1.0.2 (Beta!)</li>
            <% end %>
            <% if current_sound && current_sound.admin %>
            <li>Version 1.0.3 (Gama!)</li>
            <% end %>
            </ul>

			<br><br><br><br>
			<li>Terms of use</li>
      <br>
			General use of the website<br>
			Use of this website and corresponding services by any user entails full acceptance 
			of these terms and any specific conditions published on the website. Accordingly, users are recommended 
			to read carefully these terms and conditions and any instructions shown on the website each time they 
			access the site.	By accessing the site, you agree to these terms.
			We reserve the right to modify or delete at any time and without notice any content, services and 
			information that are published in this website, as well as limit or modify these terms and conditions. 
			<br><br><br>
			<li>About</li><br>
			Licenses<br>
			<br>What do I need to do to legally use the files on OpenSound?

			Well, it depends on what you want to do and which files you want to use. First of all, 
			OpenSound lets the user select one of three licenses for his sounds. And, we used to have a 
			4th license, which complicates matters. Depending on the license there are things you can 
			and can't do with the files. Let's start with the licenses. Creative commons has a really 
			nice page explaining them:
			<br><br>
			<li>zero (cc0): http://creativecommons.org/publicdomain/zero/1.0/</li><br>
			<li>attribution (by): http://creativecommons.org/licenses/by/3.0/</li><br>
			<li>attribution noncommercial (by-nc): http://creativecommons.org/licenses/by-nc/3.0/</li>
			<br>
			We aren't lawyers so this isn't legal advice, but here's our summary: for the "zero" license you 
			can do pretty much what you want with the sound. You could even sell the sound, ... but you can't 
			claim you are the author! For "attribution" you should always mention the original creators of the 
			sounds when you use them. "Noncommercial" works like attribution, but you can't earn any money with 
			the piece of work you create! As with all licenses the original creator can give you permission to 
			use the sound outside of the original license.
			
			<br>How do I credit/attribute?<br>
			Eg.: This [video/theatre piece/...] uses many sounds from freesound,
						for the full list see here: http://www.mysite.com/work-credits.html



			<h3> Search Users </h3>

			<%= form_tag(sounds_path, :method => "get", id: "search-form") do %>
   		 <%= text_field_tag :search, params[:search], placeholder: "Search by Tags (Eg.: Name, Genre)" %>
    	 <%= submit_tag "Search", :name => nil %>
			<% end %>


	<br>
	<h3>Latest User Accounts Created.</h3>
		<ul class="cf"><li>
			<% @sounds.each do |sound| %>
				<%= link_to sound do %>
					<li>
							<div class="sound_overview">
							<h2><%= sound.email %></h2>
						</div>
					</li>
				<% end %>
			<% end %>
			</li>
		</ul>
		<%= will_paginate @sounds, previous_label: "Previous", next_label: "Next" %>

	</div>
</div>

project/app/views/sounds/show.html.erb
<div id="sound_show">
	<div id="show_banner">
  	    <h1>User All Tracks.</h1>

    </div>
  
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>


	<div id="tracks">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @tracks.each do |track| %>
          <li class="cf">
          	<div class="track_thumbnail">
							<a href="#">
								<%= image_tag track.track_thumbnail.url(:medium) %>
							</a>
						</div>
            <div class="track_overview">
              <h2><%= link_to track.title, sound_track_path(@sound, track) %></h2>
              <p class="description"><%= truncate(track.description, lenght: 160) %></p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_sound_track_path(@sound, track) %>
                <%= link_to "Delete", sound_track_path(@sound, track), method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
              
            </div>
          </li>
        <% end %>
      </ul>
</div>

<%= will_paginate @tracks, previous_label: "Previous", next_label: "Next" %>