project/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :sounds
      resources :posts
      resources :tracks

      root to: "sounds#index"
    end
  resources :posts
  devise_for :sounds

  resources :sounds, only: [:index, :show] do
      resources :tracks
  end

  authenticated :sound do
    root 'sounds#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'


end

project/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :sound
end

project/app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_sound!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.sound = current_sound

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :text)
    end
end

project/app/helpers/posts_helper.rb
module PostsHelper
end

project/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :update %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/posts/edit.html.erb
  <div id="sound_show">
	<div id="show_banner">
	    <h1>Edit Dev Post.</h1>
    </div>
  
    <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>
  
  <div id="post">
    <div class="wrapper_skinny">

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

project/app/views/posts/index.html.erb
  <div id="sound_show">
	<div id="show_banner">
	    <h1>Updates from Developers</h1>
    </div>
  
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>

	<div id="posts">
    <div class="wrapper_skinny">

<h3>OpenSound Public Releases</h3>
<h4> 1.0.0</h4>
<ul>
<li>Basic Implementations and Funcionalities;</li>
<li>Welcome Page & Front-end;</li>
<li>Authentication Settings;</li>
<li>Dashboard & Private Content;</li>
</ul>

<h4> 1.0.1</h4>
<ul>
<li>User, Tracks & Developer Pages;</li>
<li>Improve App functions and Layout design;</li>
<li>Buttons & Stylesheets </li>
<li>Licenses & About specifications;</li>
</ul>

<% if current_sound %>
<h3>OpenSound Private Releases (Beta!)</h3> 
<h4> 1.0.2</h4>
<ul>
<li>Image multiple-format testing;</li>
<li>MP3 Audio-format;</li>
<li>Search Box & Paginate divisions;</li>
</ul>
<% end %>

<% if current_sound && current_sound.admin %>
<h3>OpenSound Developers Releases (Omega!)</h3> 
<h4> 1.0.3</h4>
<ul>
<li>Audio multiple-format testing;</li>
</ul>
<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Update</th>
      <th>Developer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= post.sound.email %></td>
        
        <% if current_sound && current_sound.admin %>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end%>
    <% end %>
  </tbody>
</table>

<br>
<% if current_sound && current_sound.admin %>
<%= link_to 'New Dev Post', new_post_path %><br>
<a href="http://localhost:3000/admin">Devs Settings</a>
<% end %>
<% end %>
<br>
<br>

project/app/views/posts/new.html.erb
<p id="notice"><%= notice %></p>

  <div id="sound_show">
	<div id="show_banner">
	    <h1>New Dev Post.</h1>
    </div>
  
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
		<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>

<div id="posts">
<div class="wrapper_skinny">


<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

project/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <div id="sound_show">
	<div id="show_banner">
	    <h1>Post Created.</h1>
    </div>
  
    <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to 'Posts', posts_path(current_sound) %></li>
        <li><%= link_to "Account Settings", edit_sound_registration_path %></li>
				<li><%= link_to "View Sounds",sounds_path %></li>

      </ul>
    </div>
  </div>
  
  <div id="post">
    <div class="wrapper_skinny">

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.sound.email %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>